POST http://localhost:2375/register 
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

###
//API2

POST http://localhost:2375/login 
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

###
//api3 

PUT http://localhost:2375/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}